artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  copy_data_dir: dataset

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/report.txt

vector_embeddings:
  root_dir: artifacts/vector_embeddings
  copy_embeds_dir: notebook exp/embeds_index
