artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  copy_data_dir: dataset
  sdg_data: artifacts/data_ingestion/SDG.pdf
  stats_data: artifacts/data_ingestion/stats.csv

data_validation:
  root_dir: artifacts/data_validation
  sdg_data: artifacts/data_ingestion/SDG.pdf
  stats_data: artifacts/data_ingestion/stats.csv
  status_file: artifacts/data_validation/report.txt

vector_embeddings:
  root_dir: artifacts/vector_embeddings
  folder_path: artifacts/vector_embeddings/embeds
